Feature: add project app
DigitalMindsUA/platform_for_juniors_backend pull request #28
Opened 2023-06-25 17:40 UTC by OlexiyVasylenkoDev

2023-06-25 18:53 UTC, HyTacker20 approved these changes

2023-06-25 20:10 UTC, sasuke13 approved these changes

2023-06-26 09:37 UTC, OleksandrZhydyk requested changes

2023-06-26 09:37 UTC, OleksandrZhydyk commented on src/config/urls.py
I believe that this way to define urls is not good.
I suggest to define app's urls in app's urls.py file and then import urls from the app as one.
Example:
```
#app urls.py
urlpatterns = [
    path('', ProductsList.as_view()),
    path('<str:slug>/', ProductView.as_view())
]

#config urls.py
api_urlpatterns = [
    path('product/', include('products.urls'), name="product")
]

urlpatterns = [
    path("api/v1/", include(api_urlpatterns))
]
```

2023-06-26 09:37 UTC, OleksandrZhydyk commented on src/converters_to_dto/converters.py
> +    @staticmethod
Do we leave DTOUnpacker?

2023-06-26 09:37 UTC, OleksandrZhydyk commented on src/core/containers.py
> +    unpack_dto = providers.Factory(DTOUnpacker)
DTOUnpacker: +, - ?

2023-06-26 09:37 UTC, OleksandrZhydyk commented on src/project/models.py
> +    specialization_slots = models.ManyToManyField(to="SpecializationSlot", blank=False)
It requires further discussion.
As I remember correctly, 'specialization_slots' is former dev_departments? I think, the Project should have onetomany relation as for every project we will create new slots

2023-06-26 12:25 UTC, HyTacker20 commented on src/converters_to_dto/converters.py
> +    @staticmethod
i use asdict() when i need to unpuck DTO

2023-06-26 14:23 UTC, HyTacker20 commented on src/project/models.py
> +    specialization_slots = models.ManyToManyField(to="SpecializationSlot", blank=False)
> It requires further discussion. As I remember correctly, 'specialization_slots' is former dev_departments? I think, the Project should have onetomany relation as for every project we will create new slots

So it means that one project has (for example) 3 specialization_slots, while another can have fully same specialization_slots, but it will be different entities? Did I understand correctly? If we use ManyToMany relation it mean that one project could have another project's specialization_slots and it is wrong.

2023-06-26 19:32 UTC, OlexiyVasylenkoDev commented on src/project/models.py
> +    specialization_slots = models.ManyToManyField(to="SpecializationSlot", blank=False)
We just don`t need to create dozens of similar instances. We will just check whether a SpecializationSlot instance with defined fields already exists and assign it to project without creating new instance

2023-06-27 09:14 UTC, OleksandrZhydyk commented on src/project/models.py
> +    specialization_slots = models.ManyToManyField(to="SpecializationSlot", blank=False)
@OlexiyVasylenkoDev Ok, maybe. Have you implemented the check? Because I have reviewed the code and haven't found where SpecializationSlot uniq checking is.

2023-06-27 09:25 UTC, OlexiyVasylenkoDev commented on src/project/models.py
> +    specialization_slots = models.ManyToManyField(to="SpecializationSlot", blank=False)
No, haven`t done it yet. Will implement this in the following commits

2023-06-27 16:08 UTC, OleksandrZhydyk commented on src/project/models.py
> +    specialization_slots = models.ManyToManyField(to="SpecializationSlot", blank=False)
Ok

2023-06-27 16:08 UTC, OleksandrZhydyk approved these changes

2023-06-27 19:07 UTC, sasuke13 approved these changes

2023-06-27 19:41 UTC, HyTacker20 approved these changes

2023-06-27 19:41 UTC, merged