Feature add project app
DigitalMindsUA/platform_for_juniors_backend pull request #35
Opened 2023-07-02 18:14 UTC by OlexiyVasylenkoDev

2023-07-02 21:42 UTC, OleksandrZhydyk requested changes

2023-07-02 21:42 UTC, OleksandrZhydyk commented on src/project/models.py
Make import USER_RELATION_MODEL dinamic, `from django.conf import settings`
And then you can use settings.USER_RELATION_MODEL

2023-07-03 10:12 UTC, OleksandrZhydyk submitted a review, later dismissed

2023-07-05 09:05 UTC, HyTacker20 approved these changes

2023-07-05 10:18 UTC, sasuke13 approved these changes

2023-07-05 10:18 UTC, sasuke13 submitted a review, later dismissed

2023-07-05 10:34 UTC, OleksandrZhydyk approved these changes

2023-07-05 10:39 UTC, sasuke13 approved these changes

2023-07-05 10:39 UTC, antony-kosenko approved these changes
LGTM!))

2023-07-05 10:40 UTC, merged